package com.redsamurai.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 16 21:17:46 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewImpl() {
        super.setNestedSelectForFullSql(false);
    }

    @Override
    protected void executeQueryForCollection(Object qc, Object[] params, int noUserParams) {
        String query = this.getQuery();
        
        String words[] = query.split(" ");
        int count = 0;
        for (int i = 0; i < words.length; i++) {
            if ("where".equalsIgnoreCase(words[i])) {
                count++;
            }
        }
        
        if (count > 1) {
            int queryWhereIndex = query.lastIndexOf("WHERE");
            String mainQuery = query.substring(0, queryWhereIndex);
            String addedWhereQuery = query.substring(queryWhereIndex, query.length());
            
            addedWhereQuery = addedWhereQuery.replaceFirst("WHERE", "and");
            
            query = mainQuery + " " + addedWhereQuery;
            
            this.setQuery(query);
        }
        
        super.executeQueryForCollection(qc, params, noUserParams);
    }
}

